services:
  web:
    build: .
    container_name: fitstagram
    ports:
      - "5000:5000"
    restart: no
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: ["./wait-for-db.sh", "db", "python", "main.py"]
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data:
